/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/userTokenMappers";
import * as Parameters from "../models/parameters";
import { OAuthApiClientContext } from "../oAuthApiClientContext";

/** Class representing a UserToken. */
export class UserToken {
  private readonly client: OAuthApiClientContext;

  /**
   * Create a UserToken.
   * @param {OAuthApiClientContext} client Reference to the service client.
   */
  constructor(client: OAuthApiClientContext) {
    this.client = client;
  }

  /**
   * @param userId
   * @param connectionName
   * @param [options] The optional parameters
   * @returns Promise<Models.UserTokenGetTokenResponse>
   */
  getToken(userId: string, connectionName: string, options?: Models.UserTokenGetTokenOptionalParams): Promise<Models.UserTokenGetTokenResponse>;
  /**
   * @param userId
   * @param connectionName
   * @param callback The callback
   */
  getToken(userId: string, connectionName: string, callback: msRest.ServiceCallback<Models.TokenResponse>): void;
  /**
   * @param userId
   * @param connectionName
   * @param options The optional parameters
   * @param callback The callback
   */
  getToken(userId: string, connectionName: string, options: Models.UserTokenGetTokenOptionalParams, callback: msRest.ServiceCallback<Models.TokenResponse>): void;
  getToken(userId: string, connectionName: string, options?: Models.UserTokenGetTokenOptionalParams, callback?: msRest.ServiceCallback<Models.TokenResponse>): Promise<Models.UserTokenGetTokenResponse> {
    return this.client.sendOperationRequest(
      {
        userId,
        connectionName,
        options
      },
      getTokenOperationSpec,
      callback) as Promise<Models.UserTokenGetTokenResponse>;
  }

  /**
   * @param userId
   * @param connectionName
   * @param [options] The optional parameters
   * @returns Promise<Models.UserTokenSignOutResponse>
   */
  signOut(userId: string, connectionName: string, options?: msRest.RequestOptionsBase): Promise<Models.UserTokenSignOutResponse>;
  /**
   * @param userId
   * @param connectionName
   * @param callback The callback
   */
  signOut(userId: string, connectionName: string, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param userId
   * @param connectionName
   * @param options The optional parameters
   * @param callback The callback
   */
  signOut(userId: string, connectionName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  signOut(userId: string, connectionName: string, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<any>): Promise<Models.UserTokenSignOutResponse> {
    return this.client.sendOperationRequest(
      {
        userId,
        connectionName,
        options
      },
      signOutOperationSpec,
      callback) as Promise<Models.UserTokenSignOutResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getTokenOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/usertoken/GetToken",
  queryParameters: [
    Parameters.userId,
    Parameters.connectionName,
    Parameters.code
  ],
  responses: {
    200: {
      bodyMapper: Mappers.TokenResponse
    },
    404: {
      bodyMapper: Mappers.TokenResponse
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};

const signOutOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "api/usertoken/SignOut",
  queryParameters: [
    Parameters.userId,
    Parameters.connectionName
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      }
    },
    204: {},
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};
