
import * as TokenModel from 'botframework-schema';
import * as ConnectorModel from 'botframework-schema';

export let typeMap: {[index: string]: any} = {
    "AadResourceUrls": TokenModel.AadResourceUrls,
    "ErrorResponse": TokenModel.ErrorResponse,
    "InnerHttpError": TokenModel.InnerHttpError,
    "ModelError": ConnectorModel.ModelError,
    "TokenResponse": ConnectorModel.TokenResponse,
    "TokenStatus": TokenModel.TokenStatus,
    "ActionTypes": ConnectorModel.ActionTypes,
    "Activity": ConnectorModel.Activity,
    "ActivityImportance": ConnectorModel.ActivityImportance,
    "ActivityTypes": ConnectorModel.ActivityTypes,
    "AnimationCard": ConnectorModel.AnimationCard,
    "Attachment": ConnectorModel.Attachment,
    "AttachmentData": ConnectorModel.AttachmentData,
    "AttachmentInfo": ConnectorModel.AttachmentInfo,
    "AttachmentLayoutTypes": ConnectorModel.AttachmentLayoutTypes,
    "AttachmentView": ConnectorModel.AttachmentView,
    "AudioCard": ConnectorModel.AudioCard,
    "BasicCard": ConnectorModel.BasicCard,
    "CardAction": ConnectorModel.CardAction,
    "CardImage": ConnectorModel.CardImage,
    "ChannelAccount": ConnectorModel.ChannelAccount,
    "ContactRelationUpdateActionTypes": ConnectorModel.ContactRelationUpdateActionTypes,
    "ConversationAccount": ConnectorModel.ConversationAccount,
    "ConversationMembers": ConnectorModel.ConversationMembers,
    "ConversationParameters": ConnectorModel.ConversationParameters,
    "ConversationReference": ConnectorModel.ConversationReference,
    "ConversationResourceResponse": ConnectorModel.ConversationResourceResponse,
    "ConversationsResult": ConnectorModel.ConversationsResult,
    "DeliveryModes": ConnectorModel.DeliveryModes,
    "EndOfConversationCodes": ConnectorModel.EndOfConversationCodes,
    "Entity": ConnectorModel.Entity,
    "Fact": ConnectorModel.Fact,
    "GeoCoordinates": ConnectorModel.GeoCoordinates,
    "HeroCard": ConnectorModel.HeroCard,
    "InputHints": ConnectorModel.InputHints,
    "InstallationUpdateActionTypes": ConnectorModel.InstallationUpdateActionTypes,
    "MediaCard": ConnectorModel.MediaCard,
    "MediaEventValue": ConnectorModel.MediaEventValue,
    "MediaUrl": ConnectorModel.MediaUrl,
    "Mention": ConnectorModel.Mention,
    "MessageReaction": ConnectorModel.MessageReaction,
    "MessageReactionTypes": ConnectorModel.MessageReactionTypes,
    "MicrosoftPayMethodData": ConnectorModel.MicrosoftPayMethodData,
    "OAuthCard": ConnectorModel.OAuthCard,
    "PagedParameters": ConnectorModel.PagedParameters,
    "RequestOptions": ConnectorModel.RequestOptions,
    "PagedMembersResult": ConnectorModel.PagedMembersResult,
    "PaymentAddress": ConnectorModel.PaymentAddress,
    "PaymentCurrencyAmount": ConnectorModel.PaymentCurrencyAmount,
    "PaymentDetails": ConnectorModel.PaymentDetails,
    "PaymentDetailsModifier": ConnectorModel.PaymentDetailsModifier,
    "PaymentItem": ConnectorModel.PaymentItem,
    "PaymentMethodData": ConnectorModel.PaymentMethodData,
    "PaymentOptions": ConnectorModel.PaymentOptions,
    "PaymentRequest": ConnectorModel.PaymentRequest,
    "PaymentRequestComplete": ConnectorModel.PaymentRequestComplete,
    "PaymentRequestCompleteResult": ConnectorModel.PaymentRequestCompleteResult,
    "PaymentRequestUpdate": ConnectorModel.PaymentRequestUpdate,
    "PaymentRequestUpdateResult": ConnectorModel.PaymentRequestUpdateResult,
    "PaymentResponse": ConnectorModel.PaymentResponse,
    "PaymentShippingOption": ConnectorModel.PaymentShippingOption,
    "Place": ConnectorModel.Place,
    "ReceiptCard": ConnectorModel.ReceiptCard,
    "ReceiptItem": ConnectorModel.ReceiptItem,
    "ResourceResponse": ConnectorModel.ResourceResponse,
    "RoleTypes": ConnectorModel.RoleTypes,
    "SemanticAction": ConnectorModel.SemanticAction,
    "SemanticActionStates": ConnectorModel.SemanticActionStates,
    "SigninCard": ConnectorModel.SigninCard,
    "SuggestedActions": ConnectorModel.SuggestedActions,
    "TextFormatTypes": ConnectorModel.TextFormatTypes,
    "TextHighlight": ConnectorModel.TextHighlight,
    "Thing": ConnectorModel.Thing,
    "ThumbnailCard": ConnectorModel.ThumbnailCard,
    "ThumbnailUrl": ConnectorModel.ThumbnailUrl,
    "TokenRequest": ConnectorModel.TokenRequest,
    "Transcript": ConnectorModel.Transcript,
    "VideoCard": ConnectorModel.VideoCard,
}


export let primitives = [
    "string",
    "boolean",
    "double",
    "integer",
    "long",
    "float",
    "number",
    "any"
 ];
 
 export let enumsMap: {[index: string]: any} = {
}
