/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ResourceResponse class.
 * @constructor
 * A response containing a resource ID
 *
 * @member {string} [id] Id of the resource
 *
 */
class ResourceResponse {
  constructor() {
  }

  /**
   * Defines the metadata of ResourceResponse
   *
   * @returns {object} metadata of ResourceResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ResourceResponse',
      type: {
        name: 'Composite',
        className: 'ResourceResponse',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ResourceResponse;
