#
# Run functional tests on browser bot deployed to Azure.
#

pool:
  vmImage: 'windows-latest'

trigger:
- main

pr:
- main

variables:
  TestResourceGroup: 'BrowserBotTest$(Build.BuildId)'
  TestAppServicePlan: 'BrowserBotServicePlan$(Build.BuildId)'
  TestWebApp: 'BrowserBotWebApp$(Build.BuildId)'
  TESTURI: 'https://$(TestWebApp).azurewebsites.net/'
#  AzureSubscription: define this in Azure

steps:

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      # Create DateTimeTag for Resource Group
      $DateTimeTag=Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"
      "##vso[task.setvariable variable=DateTimeTag]$DateTimeTag";
  displayName: 'Create DateTimeTag for Resource Group'
  # Get-Date on Azure DevOps returns a datetime relative to UTC-0, so "Z" is being used instead of the dynamic "K".

- script: yarn
  displayName: yarn install
  continueOnError: true
  enabled: false

- script: yarn browser-functional-test chrome
  displayName: run chrome tests
  continueOnError: true
  enabled: false

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      $packageName = "chromedriver";

      Write-Host "Get $packageName version tagged 'latest' from npmjs.com";

      $dist = npm dist-tag ls $packageName;
      $next = $dist.Where({$_.StartsWith("latest:")});
      [string]$latestVersion = $next.Split(':')[-1].Trim();

      $packageName;
      $latestVersion;
      "##vso[task.setvariable variable=LatestVersion;]$latestVersion";
  displayName: 'Get latest chromedriver version number from npmjs.com'
  enabled: false

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      # This lets the pipeline automatically keep up with Chrome browser releases.
      # New Chrome browser releases happen about every 4 weeks.

      $path = "$(System.DefaultWorkingDirectory)/testing/browser-functional/package.json";
      $package = 'chromedriver';
      $newVersion = "$(LatestVersion)";

      $find = "$package`": `"\S*`"";
      $replace = "$package`": `"$newVersion`"";

      Get-ChildItem -Path "$path" | % {
          $_.FullName;
          $content = Get-Content -Raw $_.FullName;

          $content -Replace "$find", "$replace" | Set-Content $_.FullName;
          '-------------'; get-content $_.FullName; '==================='
      }
  displayName: 'Upgrade chromedriver reference to latest version'
  enabled: false

- task: NodeTool@0
  displayName: use node 12.x
  inputs:
    versionSpec: 12.x

- script: cd testing/browser-functional/browser-echo-bot && yarn && yarn build
  displayName: yarn install and build browser-echo-bot

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      $registryInfo = reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version
      $chromeVersion = ($registryInfo.Split())[-2]
      $driverVersion = ($chromeVersion.Split("."))[0] + ".0.0";

      Write-Host "Chrome registry info:" $registryInfo
      Write-Host "chromedriver version needed:" $driverVersion
      "##vso[task.setvariable variable=DriverVersion;]$driverVersion";
  displayName: 'Get chromedriver version for the installed Chrome'
  continueOnError: true
  condition: succeededOrFailed()
  enabled: false

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      # Compress Bot Source Code
      cd $(System.DefaultWorkingDirectory)/testing/browser-functional/browser-echo-bot/dist
      $DirToCompress = "$(System.DefaultWorkingDirectory)/testing/browser-functional/browser-echo-bot/dist"
      $files = Get-ChildItem -Path $DirToCompress
      $ZipFileResult="$(System.DefaultWorkingDirectory)/testing/browser-functional/browser-echo-bot/browser-echo-bot.zip"
      Compress-Archive -Path $files -DestinationPath $ZipFileResult
  displayName: 'Compress Bot Source Code'

- task: AzureCLI@1
  displayName: 'Deploy browser bot'
  inputs:
    azureSubscription: '$(AzureSubscription)'
    scriptLocation: inlineScript
    inlineScript: |
     echo "# Create resource group"
     call az group create -l westus -n "$(TestResourceGroup)" --tags buildName="$(Build.DefinitionName)" cause=automation date="$(DateTimeTag)" product="$(Build.Repository.Name)" sourceBranch="$(Build.SourceBranch)"

     echo "# Create app service plan"
     call az appservice plan create -g "$(TestResourceGroup)" -n "$(TestAppServicePlan)" --number-of-workers 4 --sku S1

     echo "# Create web app"
     call az webapp create -g "$(TestResourceGroup)" -p "$(TestAppServicePlan)" -n "$(TestWebApp)"

     echo "# Deploy source code"
     call az webapp deployment source config-zip --resource-group "$(TestResourceGroup)" --name "$(TestWebApp)" --src "$(System.DefaultWorkingDirectory)/testing/browser-functional/browser-echo-bot/browser-echo-bot.zip"

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      $registryInfo = reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version
      $chromeVersion = ($registryInfo.Split())[-2]
      $driverVersion = ($chromeVersion.Split("."))[0] + ".0.0";

      Write-Host "Chrome registry info:" $registryInfo
      Write-Host "chromedriver version needed:" $driverVersion
      "##vso[task.setvariable variable=DriverVersion;]$driverVersion";
  displayName: 'Get chromedriver version for the installed Chrome'
  continueOnError: true
  condition: succeededOrFailed()
  enabled: false

- script: yarn
  displayName: yarn install

- script: yarn browser-functional-test chrome
  displayName: run chrome tests

- script: yarn browser-functional-test firefox
  displayName: run firefox tests

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      $registryInfo = reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version
      $chromeVersion = ($registryInfo.Split())[-2]
      $driverVersion = ($chromeVersion.Split("."))[0] + ".0.0";

      Write-Host "Chrome registry info:" $registryInfo
      Write-Host "chromedriver version needed:" $driverVersion
      "##vso[task.setvariable variable=DriverVersion;]$driverVersion";
  displayName: 'Get chromedriver version for the installed Chrome'
  continueOnError: true
  condition: succeededOrFailed()

- powershell: |
   cd ..
   ls -R
  displayName: Dir workspace
  enabled: false
  continueOnError: true
  condition: succeededOrFailed()

- powershell: 'gci env:* | sort-object name | Format-Table -AutoSize -Wrap'
  displayName: 'Display env vars'
  continueOnError: true
  condition: succeededOrFailed()

- task: AzureCLI@1
  displayName: 'Delete Resource Group'
  inputs:
    azureSubscription: '$(AzureSubscription)'
    scriptLocation: inlineScript
    inlineScript: 'call az group delete -n $(TestResourceGroup) --yes'

  condition: succeededOrFailed()
