// This file has been autogenerated.

exports.setEnvironment = function() {
    process.env['USER_ID'] = 'UK8CH2281:TKGSUQHQE';
    process.env['BOT_ID'] = 'BKGSYSTFG:TKGSUQHQE';
    process.env['HOST_URL'] = 'https://slack.botframework.com';
    process.env['AZURE_SUBSCRIPTION_ID'] = '0389857f-2464-451b-ac83-5f54d565b1a7';
};

exports.scopes = [[function(nock) { 
    var result = 
nock('https://token.botframework.com:443', {'encodedQueryParams':true})
    .get('/api/botsignin/GetSignInUrl')
    .query({'state':'eyJDb25uZWN0aW9uTmFtZSI6ImdpdGh1YiIsIkNvbnZlcnNhdGlvbiI6eyJtZW1iZXJzIjpbeyJpZCI6IlVLOENIMjI4MTpUS0dTVVFIUUUifV0sImJvdCI6eyJpZCI6IkJLR1NZU1RGRzpUS0dTVVFIUUUifSwidXNlciI6eyJpZCI6IlVLOENIMjI4MTpUS0dTVVFIUUUifX0sIk1zQXBwSWQiOiI5NGVhMmIwNC1jY2JhLTQzN2UtYjNmMS0zZjAzNzZmY2JjOTgifQ%3D%3D'})
    .reply(200, 'https://token.botframework.com/api/oauth/signin?signin=921d46120fc1bb20b7147f4cfb891dd8df3d50de1b', [ 'Cache-Control',
        'no-cache',
        'Pragma',
        'no-cache',
        'Content-Length',
        '97',
        'Content-Type',
        'text/html; charset=utf-8',
        'Expires',
        '-1',
        'Server',
        'Microsoft-IIS/10.0',
        'x-ms-request-id',
        '|a85d59c4ccd4374a9d36e1397f239136.6a3d7b77_',
        'X-Content-Type-Options',
        'nosniff',
        'Strict-Transport-Security',
        'max-age=31536000',
        'Set-Cookie',
        'ARRAffinity=7b75bbc2c049c7500ee5bb62a735ecc68ee15036b21d010282a620d9bca6368a;Path=/;HttpOnly;Domain=token.botframework.com',
        'Date',
        'Wed, 19 Jun 2019 22:23:47 GMT',
        'Connection',
        'close' ]);
    return result; }]];
