var fs = require('fs');

// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['USER_ID'] = 'UK8CH2281:TKGSUQHQE';
  process.env['BOT_ID'] = 'BKGSYSTFG:TKGSUQHQE';
  process.env['HOST_URL'] = 'https://slack.botframework.com';
  process.env['AZURE_SUBSCRIPTION_ID'] = '0389857f-2464-451b-ac83-5f54d565b1a7';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://slack.botframework.com:443', {"encodedQueryParams":true})
  .get('/v3/attachments/at26757-1pbNnNOTAGT-e/views/original')
  .reply(200, () => {
    return fs.createReadStream('tests/bot-framework.png');
}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '8369',
  'Content-Type',
  'image/png',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-request-id',
  '|fdd40789146b2d41a0d30295477688a3.81c137a4_',
  'Content-Disposition',
  'attachment; filename=bot-framework.png; size=8369',
  'Strict-Transport-Security',
  'max-age=31536000',
  'Date',
  'Wed, 19 Jun 2019 20:23:20 GMT',
  'Connection',
  'close' ]);
 return result; }]];