// This file has been autogenerated.

exports.setEnvironment = function() {
    process.env['USER_ID'] = 'UK8CH2281:TKGSUQHQE';
    process.env['BOT_ID'] = 'BKGSYSTFG:TKGSUQHQE';
    process.env['HOST_URL'] = 'https://slack.botframework.com';
    process.env['AZURE_SUBSCRIPTION_ID'] = '0389857f-2464-451b-ac83-5f54d565b1a7';
};

exports.scopes = [[function(nock) { 
    var result = 
nock('https://slack.botframework.com:443', {'encodedQueryParams':true})
    .filteringRequestBody(function(path) { return '*';})
    .post('/v3/conversations', '*')
    .reply(200, {'id':'BKGSYSTFG:TKGSUQHQE:DKE8NUG92'}, [ 'Cache-Control',
        'no-cache',
        'Pragma',
        'no-cache',
        'Content-Length',
        '45',
        'Content-Type',
        'application/json; charset=utf-8',
        'Expires',
        '-1',
        'Server',
        'Microsoft-IIS/10.0',
        'x-ms-request-id',
        '|fe81bad1d2462d4193b0b87782760e06.81c15013_',
        'Strict-Transport-Security',
        'max-age=31536000',
        'Date',
        'Wed, 19 Jun 2019 22:23:45 GMT',
        'Connection',
        'close' ]);
    return result; },
function(nock) { 
    var result = 
nock('https://slack.botframework.com:443', {'encodedQueryParams':true})
    .filteringRequestBody(function(path) { return '*';})
    .post('/v3/conversations/BKGSYSTFG%3ATKGSUQHQE%3ADKE8NUG92/activities', '*')
    .reply(200, {'id':'1560983025.003000'}, [ 'Cache-Control',
        'no-cache',
        'Pragma',
        'no-cache',
        'Content-Length',
        '33',
        'Content-Type',
        'application/json; charset=utf-8',
        'Expires',
        '-1',
        'Server',
        'Microsoft-IIS/10.0',
        'x-ms-request-id',
        '|8ae97eef8eb3ef4987f346c4202fa387.81c15014_',
        'Strict-Transport-Security',
        'max-age=31536000',
        'Date',
        'Wed, 19 Jun 2019 22:23:45 GMT',
        'Connection',
        'close' ]);
    return result; },
function(nock) { 
    var result = 
nock('https://slack.botframework.com:443', {'encodedQueryParams':true})
    .filteringRequestBody(function(path) { return '*';})
    .put('/v3/conversations/invalid-id/activities/1560983025.003000', '*')
    .reply(400, {'error':{'code':'ServiceError','message':'Invalid ConversationId: invalid-id'}}, [ 'Cache-Control',
        'no-cache',
        'Pragma',
        'no-cache',
        'Content-Length',
        '105',
        'Content-Type',
        'application/json; charset=utf-8',
        'Expires',
        '-1',
        'Server',
        'Microsoft-IIS/10.0',
        'x-ms-request-id',
        '|bbef0e656aadcb49ba259d2337de15be.81c15015_',
        'Strict-Transport-Security',
        'max-age=31536000',
        'Date',
        'Wed, 19 Jun 2019 22:23:45 GMT',
        'Connection',
        'close' ]);
    return result; }]];
