// This file has been autogenerated.

exports.setEnvironment = function() {
    process.env['USER_ID'] = 'UK8CH2281:TKGSUQHQE';
    process.env['BOT_ID'] = 'BKGSYSTFG:TKGSUQHQE';
    process.env['HOST_URL'] = 'https://slack.botframework.com';
    process.env['AZURE_SUBSCRIPTION_ID'] = '0389857f-2464-451b-ac83-5f54d565b1a7';
};

exports.scopes = [];
