/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";
import * as Models from "botframework-schema";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { ConnectorClientContext } from "./connectorClientContext";

class ConnectorClient extends ConnectorClientContext {
  // Operation groups
  attachments: operations.Attachments;
  conversations: operations.Conversations;

  /**
   * Initializes a new instance of the ConnectorClient class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, options?: Models.ConnectorClientOptions) {
    super(credentials, options);
    this.attachments = new operations.Attachments(this);
    this.conversations = new operations.Conversations(this);
  }
}

// Operation Specifications

export {
  ConnectorClient,
  ConnectorClientContext,
  Models as ConnectorModels,
  Mappers as ConnectorMappers
};
export * from "./operations";
