/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Model from 'botframework-schema';
import { ConversationsApi } from './conversationsApi';
import { AttachmentsApi } from './attachmentsApi';
import { MicrosoftAppCredentials } from '../auth'

class ConnectorClient {
  // Operation groups
  attachments: AttachmentsApi;
  conversations: ConversationsApi;
  /**
   * Initializes a new instance of the ConnectorClient class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param [options] The parameter options
   */
  constructor(CustomCredentials: MicrosoftAppCredentials, options?: { baseUri: string }) {    
    this.attachments = new AttachmentsApi(CustomCredentials);
    this.conversations = new ConversationsApi(CustomCredentials);

    if (options){
      this.attachments.basePath = options.baseUri;
      this.attachments.defaultHeaders = { "Content-Type": "application/json; charset=utf-8"};
      this.conversations.basePath = options.baseUri; 
      this.conversations.defaultHeaders = { "Content-Type": "application/json; charset=utf-8"};
    }
  }
}

// Operation Specifications

export {
  ConnectorClient,
  ConversationsApi,
  AttachmentsApi,
  Model as CustomTokenApiModels,
};

