/**
 * Microsoft Bot Connector API - v3.0
 * The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)    © 2016 Microsoft
 *
 * The version of the OpenAPI document: v3
 * Contact: botframework@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentAddress } from './paymentAddress';

/**
* A PaymentResponse is returned when a user has selected a payment method and approved a payment request
*/
export class PaymentResponse {
    /**
    * The payment method identifier for the payment method that the user selected to fulfil the transaction
    */
    'methodName'?: string;
    /**
    * A JSON-serializable object that provides a payment method specific message used by the merchant to process the transaction and determine successful fund transfer
    */
    'details'?: object;
    'shippingAddress'?: PaymentAddress;
    /**
    * If the requestShipping flag was set to true in the PaymentOptions passed to the PaymentRequest constructor, then shippingOption will be the id attribute of the selected shipping option
    */
    'shippingOption'?: string;
    /**
    * If the requestPayerEmail flag was set to true in the PaymentOptions passed to the PaymentRequest constructor, then payerEmail will be the email address chosen by the user
    */
    'payerEmail'?: string;
    /**
    * If the requestPayerPhone flag was set to true in the PaymentOptions passed to the PaymentRequest constructor, then payerPhone will be the phone number chosen by the user
    */
    'payerPhone'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "methodName",
            "baseName": "methodName",
            "type": "string"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "object"
        },
        {
            "name": "shippingAddress",
            "baseName": "shippingAddress",
            "type": "PaymentAddress"
        },
        {
            "name": "shippingOption",
            "baseName": "shippingOption",
            "type": "string"
        },
        {
            "name": "payerEmail",
            "baseName": "payerEmail",
            "type": "string"
        },
        {
            "name": "payerPhone",
            "baseName": "payerPhone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentResponse.attributeTypeMap;
    }
}

