/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the AttachmentInfo class.
 * @constructor
 * Metdata for an attachment
 *
 * @member {string} [name] Name of the attachment
 *
 * @member {string} [type] ContentType of the attachment
 *
 * @member {array} [views] attachment views
 *
 */
class AttachmentInfo {
  constructor() {
  }

  /**
   * Defines the metadata of AttachmentInfo
   *
   * @returns {object} metadata of AttachmentInfo
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'AttachmentInfo',
      type: {
        name: 'Composite',
        className: 'AttachmentInfo',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          views: {
            required: false,
            serializedName: 'views',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AttachmentViewElementType',
                  type: {
                    name: 'Composite',
                    className: 'AttachmentView'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = AttachmentInfo;
