/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the CardAction class.
 * @constructor
 * An action on a card
 *
 * @member {string} [type] Defines the type of action implemented by this
 * button.
 *
 * @member {string} [title] Text description which appear on the button.
 *
 * @member {string} [image] URL Picture which will appear on the button, next
 * to text label.
 *
 * @member {object} [value] Supplementary parameter for action. Content of this
 * property depends on the ActionType
 *
 */
class CardAction {
  constructor() {
  }

  /**
   * Defines the metadata of CardAction
   *
   * @returns {object} metadata of CardAction
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CardAction',
      type: {
        name: 'Composite',
        className: 'CardAction',
        modelProperties: {
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          title: {
            required: false,
            serializedName: 'title',
            type: {
              name: 'String'
            }
          },
          image: {
            required: false,
            serializedName: 'image',
            type: {
              name: 'String'
            }
          },
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'Object'
            }
          }
        }
      }
    };
  }
}

module.exports = CardAction;
