/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ConversationAccount class.
 * @constructor
 * Channel account information for a conversation
 *
 * @member {boolean} [isGroup] Is this a reference to a group
 *
 * @member {string} [id] Channel id for the user or bot on this channel
 * (Example: joe@smith.com, or @joesmith or 123456)
 *
 * @member {string} [name] Display friendly name
 *
 */
class ConversationAccount {
  constructor() {
  }

  /**
   * Defines the metadata of ConversationAccount
   *
   * @returns {object} metadata of ConversationAccount
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ConversationAccount',
      type: {
        name: 'Composite',
        className: 'ConversationAccount',
        modelProperties: {
          isGroup: {
            required: false,
            serializedName: 'isGroup',
            type: {
              name: 'Boolean'
            }
          },
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ConversationAccount;
