/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the SuggestedActions class.
 * @constructor
 * SuggestedActions that can be performed
 *
 * @member {array} [to] Ids of the recipients that the actions should be shown
 * to.  These Ids are relative to the channelId and a subset of all recipients
 * of the activity
 *
 * @member {array} [actions] Actions that can be shown to the user
 *
 */
class SuggestedActions {
  constructor() {
  }

  /**
   * Defines the metadata of SuggestedActions
   *
   * @returns {object} metadata of SuggestedActions
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SuggestedActions',
      type: {
        name: 'Composite',
        className: 'SuggestedActions',
        modelProperties: {
          to: {
            required: false,
            serializedName: 'to',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          actions: {
            required: false,
            serializedName: 'actions',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CardActionElementType',
                  type: {
                    name: 'Composite',
                    className: 'CardAction'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = SuggestedActions;
