/**
 * LUIS Runtime Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import localVarRequest = require('request');
import http = require('http');

/* tslint:disable:no-unused-locals */
import { LuisResult } from './model/luisResult';

import { ObjectSerializer, Authentication, VoidAuth } from './model/models';
import { ApiKeyAuth } from './model/models';

let luisVersion = '/luis/v2.0';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export interface PredictionResolveOptionalParams {
    /**
     * The timezone offset for the location of the request.
     */
    timezoneOffset?: number;
    /**
     * If true, return all intents instead of just the top scoring intent.
     */
    verbose?: boolean;
    /**
     * Use the staging endpoint slot.
     */
    staging?: boolean;
    /**
     * Enable spell checking.
     */
    spellCheck?: boolean;
    /**
     * The subscription key to use when enabling bing spell check
     */
    bingSpellCheckSubscriptionKey?: string;
    /**
     * Log query (default is true)
     */
    log?: boolean;

    customHeaders: {headers: {[name: string]: string}};
}

export enum LuisApikeys {
    apiKeyHeader,
}

export class LuisClient {
    protected _basePath: string = '';
    protected defaultHeaders: any = {};
    protected _useQuerystring: boolean = false;

    protected authentications = {
        'default': new VoidAuth() as Authentication,
        'apiKeyHeader': new ApiKeyAuth('header', 'Ocp-Apim-Subscription-Key'),
    }

    public constructor(basePath: string){
        if (basePath) {
            this.basePath = basePath + luisVersion;
        }
    }

    public set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    public set basePath(basePath: string) {
        this._basePath = basePath;
    }

    public get basePath(): string {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication): void {
        this.authentications.default = auth;
    }

    public setApiKey(key: LuisApikeys, value: string): void {
        (this.authentications as any)[LuisApikeys[key]].apiKey = value;
    }

    /**
     * Gets predictions for a given utterance, in the form of intents and entities. The current maximum query size is 500 characters.
     * @param query The utterance to predict.
     * @param appId The LUIS application ID (Guid).
     * @param [options] The optional parameters
     * @returns Promise<LuisResult>
     */
    public async predictionResolvePost(query: string, appId: string, options: PredictionResolveOptionalParams): Promise<LuisResult> {
        const localVarPath = this.basePath + '/apps/{appId}'
            .replace('{' + 'appId' + '}', encodeURIComponent(String(appId)));        
        let localVarQueryParameters: any = {};
        let localVarHeaderParams = (Object as any).assign({}, this.defaultHeaders) as any;
        let localVarFormParams: any = {};

        // verify required parameter 'q' is not null or undefined
        if (query === null || query === undefined) {
            throw new Error('Required parameter q was null or undefined when calling predictionResolve.');
        }

        // verify required parameter 'appId' is not null or undefined
        if (appId === null || appId === undefined) {
            throw new Error('Required parameter appId was null or undefined when calling predictionResolve.');
        }

        if (options.customHeaders === null || options.customHeaders === undefined) {
            options.customHeaders = {headers: {}}
        }

        if (options.timezoneOffset !== undefined) {
            localVarQueryParameters['timezoneOffset'] = ObjectSerializer.serialize(options.timezoneOffset, 'number');
        }

        if (options.verbose !== undefined) {
            localVarQueryParameters['verbose'] = ObjectSerializer.serialize(options.verbose, 'boolean');
        }

        if (options.staging !== undefined) {
            localVarQueryParameters['staging'] = ObjectSerializer.serialize(options.staging, 'boolean');
        }

        if (options.spellCheck !== undefined) {
            localVarQueryParameters['spellCheck'] = ObjectSerializer.serialize(options.spellCheck, 'boolean');
        }

        if (options.bingSpellCheckSubscriptionKey !== undefined) {
            localVarQueryParameters['bing-spell-check-subscription-key'] = ObjectSerializer.serialize(options.bingSpellCheckSubscriptionKey, 'string');
        }

        if (options.log !== undefined) {
            localVarQueryParameters['log'] = ObjectSerializer.serialize(options.log, 'boolean');
        }

        (Object as any).assign(localVarHeaderParams, options.customHeaders.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            maxRedirects: 21,
            body: ObjectSerializer.serialize(query, 'string')
        };

        this.authentications.apiKeyHeader.applyToRequest(localVarRequestOptions);

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<LuisResult>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, luisResult) => {
                if (error) {
                    reject(error);
                } else {
                    luisResult = ObjectSerializer.deserialize(luisResult, 'LuisResult');
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve(luisResult);
                    } else {
                        reject({
                            response: {
                                response: response,
                                headers:
                                    response.headers,
                                body: response.body,
                                status:
                                    response.statusCode
                            }
                        });
                    }
                }
            });
        });
    }
    /**
     * Gets predictions for a given utterance, in the form of intents and entities. The current maximum query size is 500 characters.
     * @param appId The LUIS application ID (guid).
     * @param query The utterance to predict.
     * @param [options] The optional parameters
     * @returns Promise<LuisResult>
     */
    public async predictionResolveGet(appId: string, query: string, options: PredictionResolveOptionalParams): Promise<LuisResult> {
        const localVarPath = this.basePath + '/apps/{appId}'
            .replace('{' + 'appId' + '}', encodeURIComponent(String(appId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams = (Object as any).assign({}, this.defaultHeaders) as any;
        let localVarFormParams: any = {};

        // verify required parameter 'appId' is not null or undefined
        if (appId === null || appId === undefined) {
            throw new Error('Required parameter appId was null or undefined when calling predictionResolve2.');
        }

        // verify required parameter 'q' is not null or undefined
        if (query === null || query === undefined) {
            throw new Error('Required parameter q was null or undefined when calling predictionResolve2.');
        }

        if (options.customHeaders === null || options.customHeaders === undefined) {
            options.customHeaders = {headers: {}}
        }

        if (query !== undefined) {
            localVarQueryParameters['q'] = ObjectSerializer.serialize(query, 'string');
        }

        if (options.timezoneOffset !== undefined) {
            localVarQueryParameters['timezoneOffset'] = ObjectSerializer.serialize(options.timezoneOffset, 'number');
        }

        if (options.verbose !== undefined) {
            localVarQueryParameters['verbose'] = ObjectSerializer.serialize(options.verbose, 'boolean');
        }

        if (options.staging !== undefined) {
            localVarQueryParameters['staging'] = ObjectSerializer.serialize(options.staging, 'boolean');
        }

        if (options.spellCheck !== undefined) {
            localVarQueryParameters['spellCheck'] = ObjectSerializer.serialize(options.spellCheck, 'boolean');
        }

        if (options.bingSpellCheckSubscriptionKey !== undefined) {
            localVarQueryParameters['bing-spell-check-subscription-key'] = ObjectSerializer.serialize(options.bingSpellCheckSubscriptionKey, 'string');
        }

        if (options.log !== undefined) {
            localVarQueryParameters['log'] = ObjectSerializer.serialize(options.log, 'boolean');
        }

        (Object as any).assign(localVarHeaderParams, options.customHeaders.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            maxRedirects: 21,
            body: ObjectSerializer.serialize(query, 'string')
        };

        this.authentications.apiKeyHeader.applyToRequest(localVarRequestOptions);

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<LuisResult>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, luisResult) => {
                if (error) {
                    reject(error);
                } else {
                    luisResult = ObjectSerializer.deserialize(luisResult, 'LuisResult');
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve(luisResult);
                    } else {
                        reject({
                            response: {
                                response: response,
                                headers:
                                    response.headers,
                                body: response.body,
                                status:
                                    response.statusCode
                            }
                        });
                    }
                }
            });
        });
    }
}
