/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a ActionParameter.
 */
class ActionParameter {
  /**
   * Create a ActionParameter.
   * @member {string} [name] Name of the parameter.
   * @member {boolean} [required] True if the parameter is required, false
   * otherwise.
   * @member {array} [value] Value of extracted entities for this parameter.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ActionParameter
   *
   * @returns {object} metadata of ActionParameter
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ActionParameter',
      type: {
        name: 'Composite',
        className: 'ActionParameter',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          required: {
            required: false,
            serializedName: 'required',
            type: {
              name: 'Boolean'
            }
          },
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'EntityElementType',
                  type: {
                    name: 'Composite',
                    className: 'Entity'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = ActionParameter;
