/**
 * Microsoft Bot Connector API - v3.0
 * The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)    © 2016 Microsoft
 *
 * The version of the OpenAPI document: v3
 * Contact: botframework@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Activity } from '../activity';
import { ChannelAccount } from '../channelAccount';
import { RequestOptions } from './requestOptions'
/**
* Parameters for creating a new conversation
*/
export class ConversationParameters extends RequestOptions {
    'continuationToken'?: string;
    /**
    * IsGroup
    */
    'isGroup'?: boolean;
    'bot'?: ChannelAccount;
    /**
    * Members to add to the conversation
    */
    'members'?: Array<ChannelAccount>;
    /**
    * (Optional) Topic of the conversation (if supported by the channel)
    */
    'topicName'?: string;
    /**
    * (Optional) The tenant ID in which the conversation should be created
    */
    'tenantId'?: string;
    'activity'?: Activity;
    /**
    * Channel specific payload for creating the conversation
    */
    'channelData'?: object;
    'channelId'?: string;
    'conversationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "continuationToken",
            "baseName": "continuationToken",
            "type": "string"
        },
        {
            "name": "isGroup",
            "baseName": "isGroup",
            "type": "boolean"
        },
        {
            "name": "bot",
            "baseName": "bot",
            "type": "ChannelAccount"
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<ChannelAccount>"
        },
        {
            "name": "topicName",
            "baseName": "topicName",
            "type": "string"
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string"
        },
        {
            "name": "activity",
            "baseName": "activity",
            "type": "Activity"
        },
        {
            "name": "channelData",
            "baseName": "channelData",
            "type": "object"
        },
        {
            "name": "conversationId",
            "baseName": "conversationId",
            "type": "string"
        },
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return this.attributeTypeMap;
    }
}

