/**
 * @module botbuilder-ai
 */
/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */
/**
 * NOTE: This class was auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * and was manually modified to make it compliant with the current implementation of the library.
 */

export interface CompositeChildModel {
    /**
    * Type of child entity.
    */
    type: string;
    /**
    * Value extracted by LUIS.
    */
    value: string;
}

export class CompositeChildModel {
    /**
    * Type of child entity.
    */
    type: string;
    /**
    * Value extracted by LUIS.
    */
    value: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            name: 'type',
            baseName: 'type',
            type: 'string'
        },
        {
            name: 'value',
            baseName: 'value',
            type: 'string'
        }    ];

    static getAttributeTypeMap() {
        return CompositeChildModel.attributeTypeMap;
    }
}
