/**
 * LUIS Runtime Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CompositeChildModel {
    /**
    * Type of child entity.
    */
    type: string;
    /**
    * Value extracted by LUIS.
    */
    value: string;
}

export class CompositeChildModel {
    /**
    * Type of child entity.
    */
    'type': string;
    /**
    * Value extracted by LUIS.
    */
    'value': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            'name': 'type',
            'baseName': 'type',
            'type': 'string'
        },
        {
            'name': 'value',
            'baseName': 'value',
            'type': 'string'
        }    ];

    static getAttributeTypeMap() {
        return CompositeChildModel.attributeTypeMap;
    }
}
