import { EntityModel, EntityWithResolutionAllOf, EntityWithResolution } from ".";

/**
 * LUIS Runtime Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EntityWithScore extends EntityModel {
    /**
    * Associated prediction score for the intent (float).
    */
    score: number;
}

export class EntityWithScore {
    /**
    * Name of the entity, as defined in LUIS.
    */
    'entity': string;
    /**
    * Type of the entity, as defined in LUIS.
    */
    'type': string;
    /**
    * The position of the first character of the matched entity within the utterance.
    */
    'startIndex': number;
    /**
    * The position of the last character of the matched entity within the utterance.
    */
    'endIndex': number;
    /**
    * Associated prediction score for the intent (float).
    */
    'score': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entity",
            "baseName": "entity",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "startIndex",
            "baseName": "startIndex",
            "type": "number"
        },
        {
            "name": "endIndex",
            "baseName": "endIndex",
            "type": "number"
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return EntityWithScore.attributeTypeMap;
    }
}
