/**
 * @module botbuilder-ai
 */
/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */
/**
 * NOTE: This class was auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * and was manually modified to make it compliant with the current implementation of the library.
 */

export interface IntentModel {
    /**
    * Name of the intent, as defined in LUIS.
    */
    intent?: string;
    /**
    * Associated prediction score for the intent (float).
    */
    score?: number;
}

export class IntentModel {
    /**
    * Name of the intent, as defined in LUIS.
    */
    intent?: string;
    /**
    * Associated prediction score for the intent (float).
    */
    score?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            name: 'intent',
            baseName: 'intent',
            type: 'string'
        },
        {
            name: 'score',
            baseName: 'score',
            type: 'number'
        }    ];

    static getAttributeTypeMap() {
        return IntentModel.attributeTypeMap;
    }
}
