name: Consumer Test

on:
  workflow_dispatch:
  push:
    branches: 
    - main
    - 4.10
    - 4.11
  pull_request:
    branches: 
    - main
    - 4.10
    - 4.11

jobs:
  build:
    name: Run test:consumer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: Run "test:consumer" npm script
        run: npm run test:consumer

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}