name: ESLint

on:
  workflow_dispatch:
  push:
    branches: 
    - main
    - 4.10
    - 4.11
  pull_request:
    branches: 
    - main
    - 4.10
    - 4.11

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      # Note: postinstall is unnecessary for linting
      - name: npm install --ignore-scripts
        run: npm install --ignore-scripts

      - name: Run "eslint" npm script
        run: npm run eslint