name: tests.yml

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - '4.12'
  pull_request:
    branches:
    - main
    - '4.12'

jobs:
  ci:
    name: "${{ github.workflow }} ${{ matrix.os }} (node ${{ matrix.node-version }})"
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, windows]
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-yarn2-${{ hashFiles('**/yarn.lock') }}

      - name: yarn
        run: yarn --immutable

      - name: yarn test:repoutils
        if: matrix.node-version == '14.x'
        run: yarn test:repoutils

      - name: yarn lint
        if: matrix.node-version == '12.x'
        run: yarn lint

      - name: yarn build
        run: yarn build

      - name: yarn test:github
        run: yarn test:github

      - name: coveralls
        if: matrix.node-version == '12.x'
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .lcov.info

      - name: yarn test:consumer
        if: matrix.node-version == '14.x'
        run: yarn test:consumer
