import * as adaptiveExpressions from 'adaptive-expressions';
import * as adaptiveExpressionsIE11 from 'adaptive-expressions-ie11';
import * as botbuilderAi from 'botbuilder-ai';
import * as botbuilderAiOrchestrator from 'botbuilder-ai-orchestrator';
import * as botbuilderApplicationInsights from 'botbuilder-applicationinsights';
import * as botbuilderAzure from 'botbuilder-azure';
import * as botbuilderAzureBlobs from 'botbuilder-azure-blobs';
import * as botbuilderCore from 'botbuilder-core';
import * as botbuilderDialogs from 'botbuilder-dialogs';
import * as botbuilderDialogsAdaptive from 'botbuilder-dialogs-adaptive';
import * as botbuilderDialogsAdaptiveTeams from 'botbuilder-dialogs-adaptive-teams';
import * as botbuilderDialogsAdaptiveTesting from 'botbuilder-dialogs-adaptive-testing';
import * as botbuilderDialogsDeclarative from 'botbuilder-dialogs-declarative';
import * as botbuilderLg from 'botbuilder-lg';
import * as botbuilderTesting from 'botbuilder-testing';
import * as botframeworkConfig from 'botframework-config';
import * as botframeworkConnector from 'botframework-connector';
import * as botframeworkSchema from 'botframework-schema';
import * as botframeworkStreaming from 'botframework-streaming';

console.log(Object.keys(adaptiveExpressions));
console.log(Object.keys(adaptiveExpressionsIE11));
console.log(Object.keys(botbuilderAi));
console.log(Object.keys(botbuilderAiOrchestrator));
console.log(Object.keys(botbuilderApplicationInsights));
console.log(Object.keys(botbuilderAzure));
console.log(Object.keys(botbuilderAzureBlobs));
console.log(Object.keys(botbuilderCore));
console.log(Object.keys(botbuilderDialogs));
console.log(Object.keys(botbuilderDialogsAdaptive));
console.log(Object.keys(botbuilderDialogsAdaptiveTeams));
console.log(Object.keys(botbuilderDialogsAdaptiveTesting));
console.log(Object.keys(botbuilderDialogsDeclarative));
console.log(Object.keys(botbuilderLg));
console.log(Object.keys(botbuilderTesting));
console.log(Object.keys(botframeworkConfig));
console.log(Object.keys(botframeworkConnector));
console.log(Object.keys(botframeworkSchema));
console.log(Object.keys(botframeworkStreaming));
